Assignment1
AntonScheitler/MolSim pull request #2
Opened 2024-10-30 20:20 UTC by AntonScheitler

The code for the first assignment

2024-11-06 11:05 UTC, manishmishra6016 requested changes
**Note**
_This is only feedback regarding the code directly. Grade feedback will be on Moodle once we are through with all groups._

-----------------------------------------------------------------------------------------------------

Thank you for the great submission :muscle: 
Just have a look at the comments and respond whenever necessary. You can implement some of the changes (except maybe do the urgent change below now) with next worksheet if you would prefer that. Mainly I found that you missed comments on certain places, position update is likely to be incorrect, but otherwise, I really liked your code in general. 

urgent changes:
- [x] correct position update/ respond if I missed something

Good luck with the second worksheet :smile:

2024-11-06 11:05 UTC, manishmishra6016 commented on README.md
> +-DDOC_TARGET=ON
mention that default is `OFF`, maybe keep default as `ON` if doxygen is found? this is just suggestion :)

2024-11-06 11:05 UTC, manishmishra6016 commented on src/computations/positions/Positions.cpp
> +            std::array<double, 3> acc = ArrayUtils::elementWiseScalarOp( (1.0 / (2 * planet.getM())), planet.getOldF(), std::multiplies<>());
`positions::stoermerVerlet()` is called first in the new iteration (before computing forces). So, the forces stored in `newF` are actually the `oldF`. You can either update the `oldF` here and use it, or directly use `newF` (and update old force while computing new ones). While the difference in results is not seen in gravitational simulation, you might see weird artifacts later on in MD simulations. Let me know if I am missing something here.

2024-11-06 11:05 UTC, manishmishra6016 commented on src/computations/velocities/Velocities.h
> +    void stoermerVerlet(ParticleContainer &planets, double deltaT);
I am generally not a fan of keeping same name for two functions, while I understand you have these under separate namespace. I would suggest refactoring slightly differently. May both position and velocity update can be under same name space `TimeDescretization`. You can also instead use a class here. This more of a suggestion, and nothing urgent, so consider it depending on if you like it and if you have time for it.

2024-11-06 11:05 UTC, manishmishra6016 commented on src/particle/Particle.h
> +class Particle {
comments about the class missing. This is generally nice to give a quick overview of what this class is about and any other relevant information.

2024-11-06 11:05 UTC, manishmishra6016 commented on src/particle/Particle.h
> +        void setX(std::array<double, 3> newX);
I would in general also recommend commenting getters and setters.

2024-11-06 11:05 UTC, manishmishra6016 commented on src/particle/ParticleContainer.h
> +        bool operator!=(const ParticleIterator &other);
doxygen comments missing

2024-11-06 11:05 UTC, manishmishra6016 commented on src/particle/ParticleContainer.h
> +    class ParticleIterator {
recommendation: you can have the iterator classes in a separate file. This would be more manageable in long term instead of nesting classes. But this is more of a matter of taste, so feel free to stick to your implementation if you prefer it.

2024-11-06 11:05 UTC, manishmishra6016 commented on src/MolSim.cpp
> +ParticleContainer particles;
I would suggest sticking to consistent style, for example either `snake_case` or `camelBack`

2024-11-06 11:05 UTC, manishmishra6016 commented on src/computations/forces/Forces.h
> +namespace forces {
I would recommend creating a force class instead of just using functions in namespace. This would be more flexible. For eg. when you add another force, you don't want to do the `oldF` update twice. This has tp be done only once. However, even with your approach, you can find a solution for it and it might be enough for the lab course. So again, it is not urgent and I leave it to your judgement.

2024-11-06 13:42 UTC, AntonScheitler commented on src/computations/positions/Positions.cpp
> +            std::array<double, 3> acc = ArrayUtils::elementWiseScalarOp( (1.0 / (2 * planet.getM())), planet.getOldF(), std::multiplies<>());
We can also just change the order of the computations correct?
So 1. force 2. position 3. velocity, correct?

2024-11-06 16:39 UTC, AntonScheitler commented on src/computations/velocities/Velocities.h
> +    void stoermerVerlet(ParticleContainer &planets, double deltaT);
Thanks for the suggestion. We decided to switch to classes for force, position and velocity calculations. We included this in the second assignment

2024-11-06 16:46 UTC, AntonScheitler commented on src/MolSim.cpp
> +ParticleContainer particles;
Thanks! This will also be adjusted in our next submission

2024-11-06 16:46 UTC, AntonScheitler commented on src/computations/forces/Forces.h
> +namespace forces {
done

2024-11-07 09:50 UTC, manishmishra6016 commented on src/computations/positions/Positions.cpp
> +            std::array<double, 3> acc = ArrayUtils::elementWiseScalarOp( (1.0 / (2 * planet.getM())), planet.getOldF(), std::multiplies<>());
Unfortunately, this won't work. As when you update the velocity, the scheme expects you to have forces computed with respect to new position, which won't be the case here (as you will not do a force calculation after position update).

The simplest solution will be to just use `f` instead of `oldF` in position update.

But according to me, the nicer approach would be to add in the beginning of position update: `oldF = f` and then you don't have to worry about it in force update, there you can just update the `f`.

2024-11-07 13:09 UTC, AntonScheitler commented on src/computations/positions/Positions.cpp
> +            std::array<double, 3> acc = ArrayUtils::elementWiseScalarOp( (1.0 / (2 * planet.getM())), planet.getOldF(), std::multiplies<>());
Ok gotcha that makes sense!

2024-11-07 21:19 UTC, FabianHaeusel commented
Hi @manishmishra6016,
you wrote in the feedback that the README is not linked to the main page of the doxygen documentation. However in the Doxyfile it is specified to show on the main page (`USE_MDFILE_AS_MAINPAGE = ./README.md`) and for me when building the doc it works. Do you have any idea on why this could happen?

2024-11-07 22:32 UTC, manishmishra6016 commented
> Hi @manishmishra6016, you wrote in the feedback that the README is not linked to the main page of the doxygen documentation. However in the Doxyfile it is specified to show on the main page (`USE_MDFILE_AS_MAINPAGE = ./README.md`) and for me when building the doc it works. Do you have any idea on why this could happen?

Hi, my bad, I updated it in the feedback :)

2024-11-08 09:12 UTC, FabianHaeusel commented
> > Hi @manishmishra6016, you wrote in the feedback that the README is not linked to the main page of the doxygen documentation. However in the Doxyfile it is specified to show on the main page (`USE_MDFILE_AS_MAINPAGE = ./README.md`) and for me when building the doc it works. Do you have any idea on why this could happen?
> 
> Hi, my bad, I updated it in the feedback :)

Thanks 😄

2024-11-08 11:41 UTC, merged